services:
  web:
    build: .
    ports:
      - "8501:8501" 
      - "5000:5000"
    environment:

      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
